@startuml
skinparam defaultTextAlignment center

' actors
'=======
:Kunde:
:Betreiber:
':Abonnent:
':Parkhausmitarbeiter:
':WeiblicherKunde:
':KundeMitFamilie:
':KundeMitBehinderung:

'system
'======
rectangle ParkhausSimulation{
    package Betrieb{
        boundary "AbonnementStarten\nSeite" as AbonnementStartenSeite
        boundary "AbonnementKuendigen\nSeite" as AbonnementKuendigenSeite
        boundary "ParkplaetzeEinsehen\nSeite" as ParkplaetzeEinsehenSeite
        '    boundary "ParkplatzErhalten\nSeite" as ParkplatzErhaltenSeite
        boundary "ParkhausEinfahren\nSeite" as ParkhausEinfahrenSeite
        boundary "ParkhausAusfahren\nSeite" as ParkhausAusfahrenSeite
        '    boundary "TicketBezahlen\nSeite" as TicketBezahlenSeite
    }

    package Verwaltung{
    boundary PreispflegeSeite
    boundary FinanzKennzahlenSeite
    boundary HistorischeBelegungSeite
    boundary UmsatzübersichtSeite
    }
}
'relations: actors - actors
'==========================
'WeiblicherKunde --|> Kunde
'KundeMitBehinderung --|> Kunde
'KundeMitFamilie --|> Kunde
'Parkhausmitarbeiter --|> Kunde

'relations: actors - boundaries
'==============================
Kunde -right- AbonnementStartenSeite
Kunde - ParkplaetzeEinsehenSeite
Kunde - AbonnementKuendigenSeite
Kunde -- ParkhausEinfahrenSeite
Kunde -right- ParkhausAusfahrenSeite

Betreiber -- PreispflegeSeite
Betreiber -- HistorischeBelegungSeite
Betreiber -- UmsatzübersichtSeite
Betreiber -- FinanzKennzahlenSeite


' fixing layout
'==============
AbonnementKuendigenSeite -[hidden]down- AbonnementStartenSeite
AbonnementStartenSeite -[hidden]down- ParkplaetzeEinsehenSeite
ParkplaetzeEinsehenSeite -[hidden]down- ParkhausEinfahrenSeite
ParkhausEinfahrenSeite -[hidden]down- ParkhausAusfahrenSeite

ParkhausAusfahrenSeite -[hidden]down- PreispflegeSeite

PreispflegeSeite -[hidden]down- HistorischeBelegungSeite
HistorischeBelegungSeite -[hidden]down- UmsatzübersichtSeite
UmsatzübersichtSeite -[hidden]down- FinanzKennzahlenSeite








@enduml