@startuml

skinparam defaultTextAlignment center

' actors
'=======
:Kunde:
:Betreiber:
':Abonnent:
':Parkhausmitarbeiter:
':WeiblicherKunde:
':KundeMitFamilie:
':KundeMitBehinderung:

'system
'======
rectangle ParkhausSimulation{
    package Betrieb{
        boundary "AbonnementVerwalten\nDisplay" as AbonnementVerwaltenDisplay
        control "AbonnementVerwalten\nController" as AbonnementVerwaltenController
        control "AbonnementStarten\nController" as AbonnementStartenController
        control "AbonnementKuendigen\nController" as AbonnementKuendigenController
        entity Abonnement

        boundary "ParkplaetzeEinsehen\nDisplay" as ParkplaetzeEinsehenDisplay
        control "ParkplaetzeEinsehen\nController" as ParkplaetzeEinsehenController
        rectangle "<<dataType>>\nBelegungAktuell" as BelegungAktuell {
        }

        boundary "ParkhausTransit\nDisplay" as ParkhausTransitDisplay
        control "ParkhausTransit\nController" as ParkhausTransitController
        control "ParkhausEinfahren\nController" as ParkhausEinfahrenController
        control "ParkhausAusfahren\nController" as ParkhausAusfahrenController
        control "ParkhausSchranke\nController" as ParkhausSchrankeController
        rectangle "<<dataType>>\nParkhausSchranke" as ParkhausSchranke {
        }
        control "Ticket\nController" as TicketController
        entity Ticket
        entity "Ticket\nWeiblicherKunde" as TicketWeiblicherKunde
        entity "Ticket\nKundeMitFamilie" as TicketKundeMitFamilie
        entity "Ticket\nKundeMitBehinderung" as TicketKundeMitBehinderung
        entity "Ticket\nParkhausmitarbeiter" as TicketParkhausmitarbeiter
        entity "Ticket\nAbonnent" as  TicketAbonnent
        rectangle "<<dataType>>\nParkplatz" as Parkplatz {
        }

    }

    package Verwaltung{
        boundary "Preispflege\nDisplay" as PreispflegeDisplay
        control "Preispflege\nController" as PreispflegeController
        entity Preis
        entity "Preis\nWeiblicherKunde" as PreisWeiblicherKunde
        entity "Preis\nKundeMitFamilie" as PreisKundeMitFamilie
        entity "Preis\nKundeMitBehinderung" as PreisKundeMitBehinderung

        boundary "FinanzKennzahlen\nDisplay" as FinanzKennzahlenDisplay
        control "FinanzKennzahlen\nController" as FinanzKennzahlenController
        entity Umsatz

        boundary "BelegungHistorisch\nDisplay" as BelegungHistorischDisplay
        control "BelegungHistorisch\nController" as BelegungHistorischController
        entity BelegungHistorisch

        boundary "Umsatzübersicht\nDisplay" as UmsatzübersichtDisplay
        control "Umsatzübersicht\nController" as UmsatzübersichtController
        entity Kennzahlen
    }
}
'relations: actors - actors
'==========================
'WeiblicherKunde --|> Kunde
'KundeMitBehinderung --|> Kunde
'KundeMitFamilie --|> Kunde
'Parkhausmitarbeiter --|> Kunde

'relations: actors - boundaries
'==============================
Kunde - AbonnementVerwaltenDisplay
Kunde -- ParkplaetzeEinsehenDisplay
Kunde - ParkhausTransitDisplay

Betreiber - PreispflegeDisplay
Betreiber - BelegungHistorischDisplay
Betreiber -- UmsatzübersichtDisplay
Betreiber - FinanzKennzahlenDisplay

'relations: boundaries - controllers
'===================================
AbonnementVerwaltenDisplay <.right. AbonnementVerwaltenController : <<use>>

ParkplaetzeEinsehenDisplay <.right. ParkplaetzeEinsehenController : <<use>>

ParkhausTransitDisplay <.right. ParkhausTransitController : <<use>>

PreispflegeDisplay <.right. PreispflegeController : <<use>>
BelegungHistorischDisplay <.right. BelegungHistorischController : <<use>>
UmsatzübersichtDisplay <.right. UmsatzübersichtController : <<use>>
FinanzKennzahlenDisplay <.right. FinanzKennzahlenController : <<use>>

'relations: controllers - others
'===============================
AbonnementVerwaltenController .right.> Abonnement : <<use>>
ParkplaetzeEinsehenController .right.> BelegungAktuell : <<use>>
ParkhausTransitController .right.> TicketController : <<use>>
ParkhausTransitController .up.> ParkhausSchrankeController : <<use>>
TicketController .right.> Ticket : <<use>>
ParkhausTransitController .down.> Parkplatz : <<use>>
ParkhausSchrankeController .right.> ParkhausSchranke : <<use>>

PreispflegeController .right.> Preis : <<use>>
BelegungHistorischController .right.> BelegungHistorisch : <<use>>
UmsatzübersichtController .right.> Umsatz : <<use>>
FinanzKennzahlenController .right.> Kennzahlen : <<use>>

' relations: entities - specializations
'======================================
Preis <|-down- PreisWeiblicherKunde
Preis <|-down- PreisKundeMitBehinderung
Preis <|-down- PreisKundeMitFamilie

Ticket <|-down- TicketKundeMitFamilie
Ticket <|-down- TicketKundeMitBehinderung
Ticket <|-down- TicketWeiblicherKunde
Ticket <|-down- TicketParkhausmitarbeiter
Ticket <|-down- TicketAbonnent

' relations: controllers - specializations
'=========================================
AbonnementVerwaltenController <|-down- AbonnementKuendigenController
AbonnementVerwaltenController <|-down- AbonnementStartenController
ParkhausTransitController <|-down- ParkhausEinfahrenController
ParkhausTransitController <|-down- ParkhausAusfahrenController

' fixing layout
'==============
AbonnementVerwaltenDisplay -[hidden]down-- ParkplaetzeEinsehenDisplay
ParkplaetzeEinsehenDisplay -[hidden]down-- ParkhausTransitDisplay
ParkhausTransitDisplay -[hidden]down-- ParkhausTransitDisplay

PreispflegeDisplay -[hidden]down-- BelegungHistorischDisplay
BelegungHistorischDisplay -[hidden]down- UmsatzübersichtDisplay
UmsatzübersichtDisplay -[hidden]down- FinanzKennzahlenDisplay

Betrieb ----[hidden]down---- Verwaltung







@enduml