@startuml

skinparam defaultTextAlignment center

' actors
'=======
:Kunde:
:Betreiber:
':Abonnent:
':Parkhausmitarbeiter:
':WeiblicherKunde:
':KundeMitFamilie:
':KundeMitBehinderung:

'system
'======
rectangle ParkhausSimulation{
    package Betrieb{
        boundary "AbonnementVerwalten\nSeite" as AbonnementVerwaltenSeite
        control "AbonnementVerwalten\nController" as AbonnementVerwaltenController
        control "AbonnementStarten\nController" as AbonnementStartenController
        control "AbonnementKuendigen\nController" as AbonnementKuendigenController
        entity Abonnement

        boundary "ParkplaetzeEinsehen\nSeite" as ParkplaetzeEinsehenSeite
        control "ParkplaetzeEinsehen\nController" as ParkplaetzeEinsehenController
        rectangle "<<dataType>>\nBelegungAktuell" as BelegungAktuell {
        }

        boundary "ParkhausTransit\nSeite" as ParkhausTransitSeite
        control "ParkhausTransit\nController" as ParkhausTransitController
        control "ParkhausEinfahren\nController" as ParkhausEinfahrenController
        control "Ticket\nController" as TicketController
        entity Ticket
        entity "Ticket\nWeiblicherKunde" as TicketWeiblicherKunde
        entity "Ticket\nKundeMitFamilie" as TicketKundeMitFamilie
        entity "Ticket\nKundeMitBehinderung" as TicketKundeMitBehinderung
        entity "Ticket\nParkhausmitarbeiter" as TicketParkhausmitarbeiter
        entity "Ticket\nAbonnent" as  TicketAbonnent
        rectangle "<<dataType>>\nParkplatz" as Parkplatz {
        }

        control "ParkhausAusfahren\nController" as ParkhausAusfahrenController
    }

    package Verwaltung{
        boundary "Preispflege\nSeite" as PreispflegeSeite
        control "Preispflege\nController" as PreispflegeController
        entity Preis
        entity "Preis\nWeiblicherKunde" as PreisWeiblicherKunde
        entity "Preis\nKundeMitFamilie" as PreisKundeMitFamilie
        entity "Preis\nKundeMitBehinderung" as PreisKundeMitBehinderung

        boundary "FinanzKennzahlen\nSeite" as FinanzKennzahlenSeite
        control "FinanzKennzahlen\nController" as FinanzKennzahlenController
        entity Umsatz

        boundary "BelegungHistorisch\nSeite" as BelegungHistorischSeite
        control "BelegungHistorisch\nController" as BelegungHistorischController
        entity BelegungHistorisch

        boundary "Umsatzübersicht\nSeite" as UmsatzübersichtSeite
        control "Umsatzübersicht\nController" as UmsatzübersichtController
        entity Kennzahlen
    }
}
'relations: actors - actors
'==========================
'WeiblicherKunde --|> Kunde
'KundeMitBehinderung --|> Kunde
'KundeMitFamilie --|> Kunde
'Parkhausmitarbeiter --|> Kunde

'relations: actors - boundaries
'==============================
Kunde - AbonnementVerwaltenSeite
Kunde -- ParkplaetzeEinsehenSeite
Kunde - ParkhausTransitSeite

Betreiber - PreispflegeSeite
Betreiber - BelegungHistorischSeite
Betreiber -- UmsatzübersichtSeite
Betreiber - FinanzKennzahlenSeite

'relations: boundaries - controllers
'===================================
AbonnementVerwaltenSeite <.right. AbonnementVerwaltenController : <<use>>

ParkplaetzeEinsehenSeite <.right. ParkplaetzeEinsehenController : <<use>>

ParkhausTransitSeite <.right. ParkhausTransitController : <<use>>

PreispflegeSeite <.right. PreispflegeController : <<use>>
BelegungHistorischSeite <.right. BelegungHistorischController : <<use>>
UmsatzübersichtSeite <.right. UmsatzübersichtController : <<use>>
FinanzKennzahlenSeite <.right. FinanzKennzahlenController : <<use>>

'relations: controllers - others
'===============================
AbonnementVerwaltenController .right.> Abonnement : <<use>>
ParkplaetzeEinsehenController .right.> BelegungAktuell : <<use>>
ParkhausTransitController .right.> TicketController : <<use>>
TicketController .right.> Ticket : <<use>>
ParkhausTransitController .down.> Parkplatz : <<use>>

PreispflegeController .right.> Preis : <<use>>
BelegungHistorischController .right.> BelegungHistorisch : <<use>>
UmsatzübersichtController .right.> Umsatz : <<use>>
FinanzKennzahlenController .right.> Kennzahlen : <<use>>

' relations: entities - specializations
'======================================
Preis <|-down- PreisWeiblicherKunde
Preis <|-down- PreisKundeMitBehinderung
Preis <|-down- PreisKundeMitFamilie

Ticket <|-down- TicketKundeMitFamilie
Ticket <|-down- TicketKundeMitBehinderung
Ticket <|-down- TicketWeiblicherKunde
Ticket <|-down- TicketParkhausmitarbeiter
Ticket <|-down- TicketAbonnent

' relations: controllers - specializations
'=========================================
AbonnementVerwaltenController <|-down- AbonnementKuendigenController
AbonnementVerwaltenController <|-down- AbonnementStartenController
ParkhausTransitController <|-down- ParkhausEinfahrenController
ParkhausTransitController <|-down- ParkhausAusfahrenController

' fixing layout
'==============
AbonnementVerwaltenSeite -[hidden]down-- ParkplaetzeEinsehenSeite
ParkplaetzeEinsehenSeite -[hidden]down-- ParkhausTransitSeite
ParkhausTransitSeite -[hidden]down-- ParkhausTransitSeite

PreispflegeSeite -[hidden]down-- BelegungHistorischSeite
BelegungHistorischSeite -[hidden]down- UmsatzübersichtSeite
UmsatzübersichtSeite -[hidden]down- FinanzKennzahlenSeite

Betrieb ----[hidden]down---- Verwaltung







@enduml